### WHEN DID THE CALCULATION, I did R^. And then you will see the Mean of Y

```{r}
rm(list = ls()); gc()
library(ISLR2)

library(readr)
library(boot)
taylor_swift_spotify <- read_csv("~/Desktop/R- Script Folder/STA 141C/taylor_swift_spotify.csv")
#View(taylor_swift_spotify)
```
```{r}
#head(taylor_swift_spotify)
#colnames(taylor_swift_spotify)

```
```{r}
TW_data = taylor_swift_spotify
#View(TW_data)

TW_data$acousticness = TW_data$acousticness *100

TW_data$danceability = TW_data$danceability * 100

TW_data$energy = TW_data$energy * 100

TW_data$speechiness = TW_data$speechiness * 100 
TW_data$liveness = TW_data$liveness * 100

TW_data$valence = TW_data$valence * 100 
TW_data$duration_ms = TW_data$duration_ms * 100
```







```{r}
set.seed(3)

rsq_function <- function(data, indices, formula) {
  d <- data[indices, ]
  fit <- lm(formula, data = d)
  return(summary(fit)$r.squared)
}


rsq1 <- boot(data = TW_data, statistic = function(data, indices) rsq_function(data, indices, popularity ~ energy + liveness + loudness + valence), R = 1000)
rsq2 <- boot(data = TW_data, statistic = function(data, indices) rsq_function(data, indices, popularity ~ energy + liveness + loudness + valence + duration_ms), R = 1000)

```

```{r}
rsq1
#plot(rsq1)
```

```{r}
rsq2
plot(rsq2)
```
```{r}
boot.ci(rsq1, type = "bca") 
```

```{r}
boot.ci(rsq2, type = "bca") 
```

```{r}
boot.fn_model_pred_mean <- function(data, index) {
  boot_sample <- data[index, ]  
  fit <- lm(popularity ~ energy + liveness + loudness + valence + duration_ms, data = boot_sample)
  predicted_popularity <- predict(fit, newdata = boot_sample)
  mean_predicted_popularity <- mean(predicted_popularity)  
  return(mean_predicted_popularity) 
}


library(boot)


boot_predicted_means <- boot(data = TW_data, statistic = boot.fn_model_pred_mean, R = 1000)

```

```{r}

set.seed(123)


mean_function <- function(data, index, formula) {
  d <- data[index, ]  # Bootstrap sample
  fit <- lm(formula, data = d)
  predicted_values <- predict(fit, newdata = d)
  mean_predicted_popularity <- mean(predicted_values)
  return(mean_predicted_popularity)
}

mean_1 <- boot(data = TW_data, statistic = function(data, indices) {
  mean_function(data, indices, popularity ~ energy + liveness + loudness + valence)
}, R = 1000)

mean_2 <- boot(data = TW_data, statistic = function(data, indices) {
  mean_function(data, indices, popularity ~ energy + liveness + loudness + valence + duration_ms)
}, R = 1000)

```
```{r}
#mean_1
boot.ci(mean_1, type = "bca")

```


```{r}
boot.ci(mean_2, type = "bca")

```

